language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.7
notifications:
    email: false
services:
  - mysql

before_install:
    - pip install black
    - pip install pydocstyle
    - pip install pytest

install:
    - python -m pip install .

before_script:
  - mysql -e "CREATE DATABASE test;"

script:
    # Run pycodestyle on all .py files in all subfolders
    - black --check .
    - find . -type d -o ! -name versioneer.py ! -name test_*.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105,D202 {} +

    # Run tests
    - export PYTHONPATH=.:$PYTHONPATH
    - cd tests
    - pytest
