name: test-comet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      USE_CCACHE: 1
      CCACHE_SLOPPINESS: pch_defines,time_macros
      CCACHE_COMPRESS: 1
      CCACHE_MAXSIZE: 250M
      #PATH: "/usr/lib/ccache:$HOME/miniconda/bin:$PATH"
      MAKEFLAGS: "-j 2"
    
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
        - 6379/tcp
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: | 
            ${{ runner.os }}-pip-
      - name: install-apt-packages
        run: |
          sudo apt-get -y install libevent-dev
          sudo apt-get -y install libboost-test-dev
          sudo apt-get -y install gcc-8
          sudo apt-get -y install g++-8
        shell: bash
      - name: setup-python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: before-install
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            black
            pydocstyle
            pytest
            pytest-asyncio
            codecov
            pytest-cov
            locust
            future
            aiohttp
      - name: install
        run: python -m pip install .
        shell: bash
      - name: before-script
        env:
          PATH: "/usr/lib/ccache:$HOME/miniconda/bin:$PATH"
        run: |
          mysql -e "CREATE DATABASE test;"
          ccache -s || true
        shell: bash
      - name: script
        env:
          PATH: "/usr/lib/ccache:$HOME/miniconda/bin:$PATH"
        run: |
          black --check .
          find . -type d -o ! -name versioneer.py ! -name test_*.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105,D202 {} +
          export PYTHONPATH=.:$PYTHONPATH
          cd tests
          pytest -x --cov=comet
          mkdir skyfield_data
          CAPUT_SKYFIELD_PATH=skyfield_data ./kotetest.sh
          ccache -s || true
        shell: bash
          
       
       
